# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 986b01bbc39e3132f36e553c85cc230a8a16714700536943b0a8a97bcc1be14151f42829ae01d988f74fe8566ab37ae52c2a5fd65e613f50d7af7cfe6d79c5b4

test:
  secret_key_base: c5e6fc03d1e94f49b6c28792693fd51f7e2d78f0bd2e38879d696c06612ab79b4410a772029de269b00a9374e0f11c92bc1f25ebabee03ef2b8c1031e99389b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
